// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewPost struct {
	Body       string  `json:"body"`
	SharedBody string  `json:"sharedBody"`
	Image      *string `json:"image"`
	Author     string  `json:"author"`
}

type NewUser struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	Confirmpassword string `json:"confirmpassword"`
}

type Post struct {
	ID         string    `json:"id"`
	Body       string    `json:"body"`
	SharedBody string    `json:"sharedBody"`
	Image      string    `json:"image"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
	SharedAt   time.Time `json:"sharedAt"`
	Author     *User     `json:"author"`
	SharedUser *User     `json:"sharedUser"`
	Likes      *User     `json:"likes"`
	Dislikes   *User     `json:"dislikes"`
	Tags       *Tag      `json:"tags"`
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
