CREATE TABLE IF NOT EXISTS Posts (
	id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
	body VARCHAR (1027) NOT NULL,
	shared_body VARCHAR (1027),
	image VARCHAR (127),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
	update_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
	shared_at TIMESTAMP WITH TIME ZONE,
	author VARCHAR (127) NOT NULL REFERENCES GoTechHUB.users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	shared_user VARCHAR (127) REFERENCES GoTechHUB.users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	likes VARCHAR (127) REFERENCES GoTechHUB.users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	Dislikes VARCHAR (127) REFERENCES GoTechHUB.users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	Tags VARCHAR (127) REFERENCES GoTechHUB.tags (id) ON DELETE CASCADE ON UPDATE CASCADE,
);